// <auto-generated />
using DbHotel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DbHotel.Migrations
{
    [DbContext(typeof(HotelContext))]
    [Migration("20220417220321_added_table_with_prices")]
    partial class added_table_with_prices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("DbHotel.ConveniencesPrice", b =>
                {
                    b.Property<int>("Convenience")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Convenience");

                    b.ToTable("ConveniencesPrices");
                });

            modelBuilder.Entity("DbHotel.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int?>("ConveniencesPriceConvenience")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRoomAvalible")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConveniencesPriceConvenience");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DbHotel.Room", b =>
                {
                    b.HasOne("DbHotel.ConveniencesPrice", "ConveniencesPrice")
                        .WithMany()
                        .HasForeignKey("ConveniencesPriceConvenience");

                    b.Navigation("ConveniencesPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
